spring.datasource.url=jdbc:postgresql://localhost:5432/xsdPractice
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver